import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// This file was generated by Antigravity to prepare your project for Firebase.
// Please replace the placeholders with your actual keys from the Firebase Console.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDUsNR8DVlvvrIUzU4dl5Zkf5oLWejGa9Y",
      authDomain: "nab3-gded.firebaseapp.com",
      projectId: "nab3-gded",
      storageBucket: "nab3-gded.firebasestorage.app",
      messagingSenderId: "540811774569",
      appId: "1:540811774569:web:38700617e47a2f310b30f8",
      measurementId: "G-45PFK7T6RV");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZwKE--BAC2fELtkZPQRq3IyU-LgLWLYA',
    appId: '1:540811774569:android:8f637babd72838b90b30f8',
    messagingSenderId: '540811774569',
    projectId: 'nab3-gded',
    storageBucket: 'nab3-gded.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_IOS_API_KEY',
    appId: '1:REPLACE_WITH_YOUR_IOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_SENDER_ID',
    projectId: 'nab3-gded',
    storageBucket: 'nab3-gded.appspot.com',
    iosBundleId: 'com.example.nab3Gded',
  );
}
